=== pyrus/Pyrus/data/channel-1.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ch="http://pear.php.net/channel-1.0" targetNamespace="http://pear.php.net/channel-1.0" elementFormDefault="qualified">
 <xs:complexType name="function">
  <xs:simpleContent>
   <xs:extension base="xs:string">
    <xs:attribute name="version" use="required">
     <xs:simpleType>
      <xs:restriction base="xs:string">
       <xs:pattern value="[0-9]+\.[0-9]+"/>
      </xs:restriction>
     </xs:simpleType>
    </xs:attribute>
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 <xs:complexType name="functions">
  <xs:sequence>
   <xs:element name="function" type="ch:function" maxOccurs="unbounded"/>
  </xs:sequence>
 </xs:complexType>
 <xs:complexType name="serverinternals">
  <xs:sequence>
   <xs:element name="xmlrpc" minOccurs="0">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="ch:functions">
       <xs:attribute name="path" type="xs:string"/>
      </xs:extension>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="rest" minOccurs="0">
    <xs:complexType>
     <xs:sequence>
      <xs:element name="baseurl" maxOccurs="unbounded">
       <xs:complexType>
        <xs:simpleContent>
         <xs:extension base="xs:string">
          <xs:attribute name="type" type="xs:string" use="required"/>
         </xs:extension>
        </xs:simpleContent>
       </xs:complexType>
      </xs:element>
     </xs:sequence>
    </xs:complexType>
   </xs:element>
   <xs:element name="soap" minOccurs="0">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="ch:functions">
       <xs:attribute name="path" type="xs:string"/>
      </xs:extension>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
  </xs:sequence>
  <xs:attribute name="port" type="xs:int" default="80"/>
  <xs:attribute name="ssl">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="yes"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
 </xs:complexType>
 <xs:complexType name="mirrorinternals">
  <xs:sequence>
   <xs:element name="xmlrpc" minOccurs="0">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="ch:functions">
       <xs:attribute name="path" type="xs:string"/>
      </xs:extension>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="rest" minOccurs="0">
    <xs:complexType>
     <xs:sequence>
      <xs:element name="baseurl" maxOccurs="unbounded">
       <xs:complexType>
        <xs:simpleContent>
         <xs:extension base="xs:string">
          <xs:attribute name="type" type="xs:string" use="required"/>
         </xs:extension>
        </xs:simpleContent>
       </xs:complexType>
      </xs:element>
     </xs:sequence>
    </xs:complexType>
   </xs:element>
   <xs:element name="soap" minOccurs="0">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="ch:functions">
       <xs:attribute name="path" type="xs:string"/>
      </xs:extension>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
  </xs:sequence>
  <xs:attribute name="port" type="xs:int" default="80"/>
  <xs:attribute name="host" use="required"/>
  <xs:attribute name="ssl">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="yes"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
 </xs:complexType>
 <xs:complexType name="server">
  <xs:sequence>
   <xs:element name="primary">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="ch:serverinternals"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="mirror" type="ch:mirrorinternals" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
 </xs:complexType>
 <xs:complexType name="validatepackage">
  <xs:simpleContent>
   <xs:extension base="xs:string">
    <xs:attribute name="version"/>
   </xs:extension>
  </xs:simpleContent>
 </xs:complexType>
 <xs:simpleType name="channelname">
  <xs:restriction base="xs:string">
   <xs:pattern value="[A-Za-z][A-Za-z0-9_.]+((/[A-Za-z0-9]+)+)?|__uri"/>
  </xs:restriction>
 </xs:simpleType>
 <xs:element name="channel">
  <xs:complexType>
   <xs:sequence>
    <xs:element name="name" type="ch:channelname"/>
    <xs:choice>
     <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="suggestedalias" type="ch:channelname"/>
      <xs:element name="summary" type="xs:string"/>
     </xs:sequence>
     <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="summary" type="xs:string"/>
      <xs:element name="suggestedalias" minOccurs="0" type="ch:channelname"/>
     </xs:sequence>
    </xs:choice>
    <xs:element name="validatepackage" minOccurs="0">
     <xs:complexType>
      <xs:simpleContent>
       <xs:restriction base="ch:validatepackage">
        <xs:pattern value="[A-Za-z][a-zA-Z0-9_]+"/>
       </xs:restriction>
      </xs:simpleContent>
     </xs:complexType>
    </xs:element>
    <xs:element name="servers" type="ch:server"/>
    <xs:element name="validatepackage" minOccurs="0">
     <xs:complexType>
      <xs:simpleContent>
       <xs:restriction base="ch:validatepackage">
        <xs:pattern value="[A-Za-z][a-zA-Z0-9_]+"/>
       </xs:restriction>
      </xs:simpleContent>
     </xs:complexType>
    </xs:element>
    <xs:element name="_lastmodified" minOccurs="0" maxOccurs="1">
     <xs:complexType mixed="true">
      <xs:sequence minOccurs="0" maxOccurs="1">
       <xs:element name="ETag" minOccurs="0" type="xs:string"/>
       <xs:element name="Last-Modified" minOccurs="0" type="xs:string"/>
      </xs:sequence>
     </xs:complexType>
    </xs:element>
   </xs:sequence>
   <xs:attribute name="version" use="required">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+\.[0-9]+"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== pyrus/Pyrus/tests/ChannelRegistry/sample_channel.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<channel version="1.0" xmlns="http://pear.php.net/channel-1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://pear.php.net/dtd/channel-1.0 http://pear.php.net/dtd/channel-1.0.xsd">
 <name>pear.unl.edu</name>
 <summary>UNL PHP Extension and Application Repository</summary>
 <suggestedalias>unl</suggestedalias>
 <servers>
  <primary>
   <rest>

    <baseurl type="REST1.0">http://pear.unl.edu/Chiara_PEAR_Server_REST1.0/</baseurl>
    <baseurl type="REST1.1">http://pear.unl.edu/Chiara_PEAR_Server_REST1.1/</baseurl>
    <baseurl type="REST1.3">http://pear.unl.edu/Chiara_PEAR_Server_REST1.3/</baseurl>
   </rest>
  </primary>
 </servers>
</channel>
